services:
  database:
    build:
      network: host
    container_name: gosource-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:alpine
    ports:
      - "${DATABASE_PORT}:5432"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      network: host
    container_name: gosource-backend
    depends_on:
      - database
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${DATABASE_PORT}/${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:3000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      network: host
    container_name: gosource-frontend
    depends_on:
      - backend
    environment:
      CI: true
      NODE_ENV: production
    ports:
      - "${FRONTEND_PORT}:80"
