services:
  database:
    container_name: gosource-database
    environment:
      POSTGRES_DB: gosource
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    image: postgres:alpine
    ports:
      - "127.0.0.1:${DATABASE_PORT-5432}:5432"
      - "[::1]:${DATABASE_PORT-5432}:5432"
