services:
  database:
    container_name: gosource-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:alpine
    ports:
      - "127.0.0.1:${DATABASE_PORT}:5432"
      - "[::1]:${DATABASE_PORT}:5432"
